### PR TITLE
Add article and articles landing page

### PR DESCRIPTION
**Pull request by prgriffithsdev**
Hopefully, I understood your comment correctly last night. If not feel free to rip it apart and refactor, or send me the instructions :). I have added a new article and article landing page doctype and to accompany this change I have added some compositions such as standard page (you may want this to be the content page) and page panner. The idea is that a landing page will have the option to have a page banner (or hero). A standard page doesn't have this at the moment but you can easily tweak this by adding the page banner composition. 

I have created some temporary markup and added a bootstrap 4 CDN so that I can see it rendering out, this is all temporary and when we can refactor as we like! I have added some test content and included the usync files, hopefully, i haven't missed anything. I originally added the new pages to the non profit ord website container but had to move them to the website container as so

image

I was seeing this - tried resetting cache (from settings), etc but no luck - let me know if i missed something

image

I have added some custom data types such as image croppers (with temp crops) and radio button selectors as discussed. I added some labels to the SEO composition. The render of the images may need so work but let me know, its been a while.

Hopefully, this is a good start, and feel free to fire over some edits so its fit for purpose. Ive left some comments to note my thoughts.

Should look something like so if all merged in correctly 

image

image

Thanks 
Paul

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Sweet, great work! But build check is failing, looks like 2 files are missing from your commit... 2 model files

CSC : error CS2001: Source file 'C:\projects\umbraco-v8-community-website-starterkit\source\Core\Models\Generated\**PageBanner.generated.cs**' could not be found. [C:\projects\umbraco-v8-community-website-starterkit\source\Core\Core.csproj]
  CSC : error CS2001: Source file 'C:\projects\umbraco-v8-community-website-starterkit\source\Core\Models\Generated\**StandardPage.generated.cs**' could not be found. [C:\projects\umbraco-v8-community-website-starterkit\source\Core\Core.csproj]

**Comment by prgriffithsdev** [comment]
Hey @TimGeyssens, I've added the two missing models and the build is verified 🕺

**Comment by TimGeyssens** [comment]
Awesome! Will merge once I'm back home later today

**Comment by TimGeyssens** [comment]
Merged, did some very minor tweaks (mainly naming), thanks for the help!

**Pull request merged**
