### PR TITLE
55 setup navs on website doctype

### PR DESCRIPTION
**Pull request by AaronSadlerUK**
Configured the main and footer navigations to use MegaNavV8

### CODE REVIEW

**Comment by TimGeyssens** [comment]
Nice, mind sharing a screenshot of the doctypes? Since from what I can see in the uSync files it seems a bit odd...

**Comment by AaronSadlerUK** [comment]
Sure for site wide navigation i would usually look to install into a global settings node of some kind.

This kit doesn't have that (maybe it needs adding?)

As such i have made a folder in root instead.

I'll send some screenshots when I'm back home

**Comment by TimGeyssens** [comment]
@AaronSadlerUK  yes it has a website node :) that is site wide :) other pages wil be underneath that, ace!

**Comment by TimGeyssens** [comment]
only odd thing seems the MegaNavV8 model and doc type...

**Comment by AaronSadlerUK** [comment]
In the current setup (which imo is incorrect) the home page would start with a url structure of /home
I didn't want to mess with this, but 99% of sites have this on / not /home.

Traditionally I would have a node at root node called Global Settings, this would contain such things as the logo etc...
And then the ability to make child nodes of the MegaNavV8 document type this is to allow for multiple menus to be created easily.
Also when you add multiple links / levels to the menu, the property editor can get rather long, so keeping it in its own node allows for that UI to grow without shifting other parts down.

image

image

image

image

**Comment by TimGeyssens** [comment]
@AaronSadlerUK yeah /home will go away :) but we are using tabs so don't worry about the UI :) mind moving it around a bit? Just 2 properties of type meganav (one with 2 levels for main, 1 for a single level for footer)  on the website doctype... does that make sense? Cheers :)

**Comment by TimGeyssens** [comment]
@AaronSadlerUK added a discussion #57

**Comment by AaronSadlerUK** [comment]
@TimGeyssens I'm quite happy to do this, however it would remove the ease of being able to just create a new menu from the backoffice.
It would also make make the settings tab rather long and messy once many links are added?
And possibly confusing with two of the menu on the same tab

**Comment by AaronSadlerUK** [comment]
I have done this on the home node in this branch:

https://github.com/AaronSadlerUK/Umbraco-v8-Community-Website-StarterKit/commit/e1387b6a190762e4b91a99847d2e6bc5bc5bda03

image

**Comment by TimGeyssens** [comment]
Ok thanks for updating, I guess in that case we don't need the MegaNavV8 doctype right? And Model? Happy to merge if you are :) Might still change the way you said but in this case it's a rather small site..thanks for the help so far :)

**Comment by AaronSadlerUK** [comment]
I have made a new PR containing the above changes
https://github.com/TimGeyssens/Umbraco-v8-Community-Website-StarterKit/pull/58

**Pull request closed without merging**
